spring:
  datasource:
    bus-schedule:
      url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false
      username: root
      password: test
      driverClassName: com.mysql.jdbc.Driver
    dininghall-menu:
      url: jdbc:mysql://127.0.0.1:3306/testdb2?useSSL=false
      username: root
      password: test
      driverClassName: com.mysql.jdbc.Driver
    no-class-info:
          url: jdbc:mysql://127.0.0.1:3306/no_class_info?useSSL=false
          username: root
          password: test
          driverClassName: com.mysql.jdbc.Driver

